services:
  redis:
    image: redis:7.4.8-alpine
    # container_name: shop_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s

  api:
    image: shop-bot.cr.cloud.ru/shop-api:v1.0
    expose: 
      - 8000
    depends_on:
      - redis
    restart: unless-stopped
  worker:
    image: shop-bot.cr.cloud.ru/shop-worker:v1.1
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data: